#ifndef __WINDOW_FUNCTION__DEF_H
#define __WINDOW_FUNCTION__DEF_H

#define NUM_WINDOW_FUNCTIONS 5

#define WINDOW_FUNCTION_NONE 		0
#define WINDOW_FUNCTION_HANNING 	1
#define WINDOW_FUNCTION_HAMMING 	2
#define WINDOW_FUNCTION_FLATTOP 	3
#define WINDOW_FUNCTION_BARTLETT	4

#endif // __WINDOW_FUNCTION__DEF_H
